version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME:-fraudshield}
      - CORS_ORIGINS=*
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL:-http://localhost:8000}
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-fraudshield}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
